### ISSUE TITLE
Default to download data into current working directory instead of ./data

### ISSUE THREAD

**Issue by tomplex** [SimmonsRitchie/get-pop#19]
I think overall when creating a tool which you intend to distribute, it's best to assume as little about what the user wants as possible, and creating a new directory on the user's machine when they haven't specified any location to put the data is a little heavy-handed. What's more is that the vast majority of UNIX-based tools operate on the current working directory by default, so doing the same here will improve intuitiveness of the tool.

**Comment by SimmonsRitchie** [comment]
Great suggestion. I hadn't considered that at all.
